# Generated by Django 5.0.1 on 2024-01-12 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_livros_data_emprestimo_alter_livros_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_emprestimo',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
